import fs from 'node:fs';
import { createRequire } from 'node:module';
import { launch, loginContext, watch, fixtures, BASE } from './lib.mjs';
const require = createRequire(new URL('../../package.json', import.meta.url));
const { Client } = require('pg');
const F = fixtures();
const errors = [];
const browser = await launch();
const page = await (await loginContext(browser, 'qa_admin', 'QaPrueba#2026')).newPage();
watch(page, 'qa_admin', errors);
await page.goto(`${BASE}/issued-invoices`);
await page.waitForTimeout(2500);
await page.locator('input[type=file]:not([webkitdirectory])').first().setInputFiles({ name: 'QA-factura-emitida.xml', mimeType: 'text/xml', buffer: fs.readFileSync(F.xml) });
await page.waitForTimeout(5000);
const t = (await page.locator('body').innerText()).replace(/\s+/g, ' ');
console.log('UI:', t.match(/(\d+ (factura|importad)[^.]{0,80}|Error[^.]{0,120}|duplicad[^.]{0,60})/g)?.slice(0, 3));
const db = new Client({ host: '127.0.0.1', port: 54322, user: 'postgres', database: 'postgres' });
await db.connect();
console.log('BD issued_invoices:', (await db.query("select uuid, xml_url from issued_invoices where uuid='11111111-2222-3333-4444-555555555555'")).rows);
await db.end();
console.log(errors.filter((e) => e.kind === 'http').map((e) => e.text.slice(0, 220)));
await browser.close();
