-- Base "clients" table.
-- In the legacy project this table was created manually from the Supabase
-- dashboard, so it was never captured in a migration. The later migration
-- 20260228190203_add_cfdi_columns_to_clients.sql does `ALTER TABLE clients ...`
-- and assumed it already existed. This migration creates the base table so the
-- whole schema is reproducible from migrations alone.
--
-- id is BIGINT identity to match foreign keys such as
-- quotations.client_id BIGINT REFERENCES public.clients(id).

CREATE TABLE IF NOT EXISTS public.clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
